#!/bin/bash
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 0 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
for seed in $(seq 53 75)
  do
    python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t50 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $seed --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
  done

#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
