#~/bin/bash

#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 0 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 1 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 16 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 17 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 18 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 19 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 20 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 21 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 22 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 23 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 24 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 25 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 26 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 27 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 28 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 29 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 30 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 31 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 32 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 33 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 34 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 35 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 36 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 37 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 38 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 39 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 40 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 41 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 42 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 43 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 44 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 45 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 46 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 47 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 48 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 49 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
#python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 50 --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb

for seed in $(seq 61 100)
do
    python main.py --config bedroom_ls_opt.yml --model Diffusion --exp lsun_orig --image_folder lsun_bedroom_images --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $seed --tau 0.1 --no_augmentation --pg_steps 1 --use_pretrained --use_wandb
done
