#!/bin/bash
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 1 --tau 0.5 --use_wandb --no_augmentation

#for seed in $(seq 1 50)
#    do
#        python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $seed --tau 0.5 --use_wandb --no_augmentation
#    done


#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 51 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 52 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 53 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 54 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 55 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 56 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 57 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 58 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 59 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 60 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 61 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 62 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 63 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 64 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 65 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 66 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 67 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 68 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 69 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 70 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 71 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 72 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 73 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 74 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 75 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 76 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 77 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 78 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 79 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 80 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 81 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 82 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 83 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 84 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 85 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 86 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 87 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 88 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 89 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 90 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 91 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 92 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 93 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 94 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 95 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 96 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 97 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 98 --tau 0.5 --use_wandb --no_augmentation
python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 99 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 100 --tau 0.5 --use_wandb --no_augmentation
