#!/bin/bash
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 0 --tau 0.1 --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20 --use_wandb
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 1 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 16 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 17 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 18 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 19 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
#python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t100-parallel --doc cifar10-orig --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 20 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20

for i in $(seq 1 100)
do
    python main.py --config cifar10_ls_opt.yml --model Diffusion --exp cifar10-orig-exp --image_folder cifar10-inverse-t10-parallel --doc cifar10-orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $i --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 --m 3 --max_anderson_iters 20
done
