#!/bin/bash
for seed in $(seq 21 30)
  do
    python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $seed --tau 0.1 --use_wandb --no_augmentation
  done
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t100-seq --doc celeba-orig-ddim --ls_opt --timesteps 100 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 1 --tau 0.5 --use_wandb --no_augmentation

#for seed in $(seq 1 50)
#    do
#        python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $seed --tau 0.5 --use_wandb --no_augmentation
#    done


#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 16 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 17 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 18 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 19 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 20 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 21 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 22 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 23 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 24 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 25 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 26 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 27 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 28 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 29 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 30 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 31 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 32 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 33 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 34 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 35 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 36 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 37 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 38 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 39 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 40 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 41 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 42 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 43 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 44 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 45 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 46 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 47 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 48 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 49 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 50 --tau 0.5 --use_wandb --no_augmentation
