#!/bin/bash
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 0 --tau 0.1 --no_augmentation --pg_steps 1 --use_wandb
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 1 --tau 0.1 --no_augmentation --pg_steps 1 --use_wandb
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
#python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
python main.py --config celeba_ls_opt.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-parallel --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --tau 0.1 --use_wandb --no_augmentation --pg_steps 1 
