#!/bin/bash

#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --tau 0.5 --use_wandb --no_augmentation
#python main.py --config celeba_ls_opt_seq.yml --model Diffusion --exp celeba-orig --image_folder celeba-inverse-t20-seq --doc celeba-orig-ddim --ls_opt --timesteps 20 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --tau 0.5 --use_wandb --no_augmentation
