#~/bin/bash
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 0 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 1 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 2 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 3 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 4 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 5 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 6 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 7 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 8 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 9 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 10 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 11 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 12 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 13 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 14 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 15 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 16 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 17 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 18 --no_augmentation --use_pretrained --use_wandb
#python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed 19 --no_augmentation --use_pretrained --use_wandb
for seed in $(seq 1 100)
    do
        python main.py --config church_ls_opt_seq.yml --model Diffusion --exp lsun_orig --image_folder lsun_church_seq_images_t10 --doc lsun_orig --ls_opt --timesteps 10 --ni --method default --lambda1 1 --lambda2 0 --lambda3 0 --seed $seed --no_augmentation --use_pretrained --use_wandb
    done
